### ISSUE TITLE
email verification

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#110]
Before we can get SES turned on in AWS, we need email verification. This would include the following:
* Don't allow login emails to be sent until initial invitation is accepted
* If an email bounces, prevent the app from sending emails to that address

**Comment by arrocke** [comment]
@Pertempto Can you think of anything else we need to handle here to get SES turned on?

**Comment by arrocke** [comment]
## TODO
- [x] accept invitation view
- [x] verify email on accept invitation
- [x] don't send emails to unverified emails
- [x] handle bounces and complaints from SES
