### ISSUE TITLE
Sidebar for lexicons

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#252]
## Acceptance criteria

* Clicking the original language text will open the sidebar on the right side (left for rtl languages)
* The sidebar should show the word and the strongs number
* Below the word should be the formatted BDB, or LSJ content
* Sidebar should should remain open until you close it
* Sidebar should show loading spinner while data loads
* Pressing Ctrl + D while a gloss input is focused will open the menu. While the menu is open, pressing Ctrl + D will close it regardless of what is focused
* Design shows tabs, but for now we will just show the lexicon data

## Design

![Image](https://github.com/arrocke/gloss-translation/assets/11968925/22b8a02c-17bd-4e6e-9744-3f2a893d8f3d)

[Figma](https://www.figma.com/file/GYKTJWl1otgwpmA9ZLLthE/Gloss-Translation-App?type=design&node-id=1023-276&mode=design&t=1ag7J6V2LBpMFujr-0)

## Todo
- [x] Figma design
- [ ] Implementation

**Comment by Pertempto** [comment]
Is there any particular react sidebar component that we want to use?

**Comment by Pertempto** [comment]
Ah, this should be simple to make myself. For some reason I was imagining a resizable sidebar, which would be trickier.

**Comment by Pertempto** [comment]
* [x] Clicking the original language text will open the sidebar on the right side (left for rtl languages)
* [x] The sidebar should show the word and the strongs number
* [x] Track word index, not word ID
* [x] Below the word should be the formatted BDB, or LSJ content
    * [x] Markdown integration
* [x] Sidebar should should remain open until you close it
* [x] Sidebar should show loading spinner while data loads
* [x] Revert API
* [x] Pressing Ctrl + D while a gloss input is focused will open the menu. While the menu is open, pressing Ctrl + D will close it regardless of what is focused
* [x] Automatically show first word of the verse, when a new verse is selected.
* [x] Sidebar should stay in sync with currently focused word input
* [x] Mobile layout
* [x] Figure out scroll/height

**Comment by Pertempto** [comment]
@arrocke what do you think of having the sidebar open by default? That will make it more discoverable, otherwise people probably won't find it unless we prompt them to or they click on a word accidentally.

**Comment by Pertempto** [comment]
How should the sidebar look on mobile?

**Comment by Pertempto** [comment]
Here's the basic look I've got so far. It will quickly show us where we additional clean up work in the lemma resource data! (I think I can improve the regexes to remove the extra whitespace that is messing up the markdown formatter)

I need to do work on constraining the height so that you can scroll the sidebar separately

![2023-11-21 05 37 54 localhost 80821406b362](https://github.com/arrocke/gloss-translation/assets/17209828/acf9f4ec-79c8-4dcd-80c2-f3dc9fd6042d)

**Comment by arrocke** [comment]
> what do you think of having the sidebar open by default?

In many cases, the translator is going to quickly tab through the page because the suggestions will be pretty good. If we leave this open, it will be a distraction because it has to load continually.

> How should the sidebar look on mobile?

How's this?
![main screen - v3](https://github.com/arrocke/gloss-translation/assets/11968925/79aeca34-7d79-432e-ad96-0f47a86f2fca)
